name: geonera-geonera-ai
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12

  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1

  - pandas
  - numpy
  - scipy
  - scikit-learn
  - pyarrow
  - numba
  - catboost
  - shap
  - optuna
  - tqdm

  - clickhouse-driver
  - python-dotenv
  - lz4
  - python-telegram-bot

  - pip
  - pip:
    - clickhouse-cityhash==1.0.2.5
    - pandas-stubs==2.3.2.250926
    - scipy-stubs==1.16.3.0